name: 'Hello and Goodbye Action'
description: 'A composite action to say hello and goodbye'
inputs:
  name:
    description: 'Name to greet'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Set executable permissions for scripts
      run: chmod +x ./scripts/hello.sh ./scripts/goodbye.sh
      shell: bash
      
    - name: Say Hello
      run: ./scripts/hello.sh
      shell: bash
      env:
        NAME: ${{ inputs.name }}

    - name: Say Goodbye
      run: ./scripts/goodbye.sh
      shell: bash
      env:
        NAME: ${{ inputs.name }}
